//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyWork.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class CompanyDBEntities : DbContext
    {
        public CompanyDBEntities()
            : base("name=CompanyDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Announcement> Announcement { get; set; }
        public DbSet<Department> Department { get; set; }
        public DbSet<IsRead> IsRead { get; set; }
        public DbSet<MeetingRoom> MeetingRoom { get; set; }
        public DbSet<Registration> Registration { get; set; }
        public DbSet<Reimburse> Reimburse { get; set; }
        public DbSet<Subscribe> Subscribe { get; set; }
        public DbSet<Travelinfo> Travelinfo { get; set; }
        public DbSet<Userinfo> Userinfo { get; set; }
        public DbSet<Vacateinfo> Vacateinfo { get; set; }
    
        public virtual ObjectResult<proc_AlreadyReimburse_Result> proc_AlreadyReimburse(string u_ID, Nullable<bool> isApprove)
        {
            var u_IDParameter = u_ID != null ?
                new ObjectParameter("U_ID", u_ID) :
                new ObjectParameter("U_ID", typeof(string));
    
            var isApproveParameter = isApprove.HasValue ?
                new ObjectParameter("IsApprove", isApprove) :
                new ObjectParameter("IsApprove", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_AlreadyReimburse_Result>("proc_AlreadyReimburse", u_IDParameter, isApproveParameter);
        }
    
        public virtual ObjectResult<proc_AlreadyTravel_Result> proc_AlreadyTravel(string u_ID, Nullable<bool> isApprove)
        {
            var u_IDParameter = u_ID != null ?
                new ObjectParameter("U_ID", u_ID) :
                new ObjectParameter("U_ID", typeof(string));
    
            var isApproveParameter = isApprove.HasValue ?
                new ObjectParameter("IsApprove", isApprove) :
                new ObjectParameter("IsApprove", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_AlreadyTravel_Result>("proc_AlreadyTravel", u_IDParameter, isApproveParameter);
        }
    
        public virtual ObjectResult<proc_AlreadyVacate_Result> proc_AlreadyVacate(string u_ID, Nullable<bool> isApprove)
        {
            var u_IDParameter = u_ID != null ?
                new ObjectParameter("U_ID", u_ID) :
                new ObjectParameter("U_ID", typeof(string));
    
            var isApproveParameter = isApprove.HasValue ?
                new ObjectParameter("IsApprove", isApprove) :
                new ObjectParameter("IsApprove", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_AlreadyVacate_Result>("proc_AlreadyVacate", u_IDParameter, isApproveParameter);
        }
    
        public virtual int proc_insertRoom(Nullable<int> m_ID, Nullable<System.DateTime> m_Date, string s_StartTime, string s_EndTime, string s_Title, Nullable<int> s_U_ID)
        {
            var m_IDParameter = m_ID.HasValue ?
                new ObjectParameter("M_ID", m_ID) :
                new ObjectParameter("M_ID", typeof(int));
    
            var m_DateParameter = m_Date.HasValue ?
                new ObjectParameter("M_Date", m_Date) :
                new ObjectParameter("M_Date", typeof(System.DateTime));
    
            var s_StartTimeParameter = s_StartTime != null ?
                new ObjectParameter("S_StartTime", s_StartTime) :
                new ObjectParameter("S_StartTime", typeof(string));
    
            var s_EndTimeParameter = s_EndTime != null ?
                new ObjectParameter("S_EndTime", s_EndTime) :
                new ObjectParameter("S_EndTime", typeof(string));
    
            var s_TitleParameter = s_Title != null ?
                new ObjectParameter("S_Title", s_Title) :
                new ObjectParameter("S_Title", typeof(string));
    
            var s_U_IDParameter = s_U_ID.HasValue ?
                new ObjectParameter("S_U_ID", s_U_ID) :
                new ObjectParameter("S_U_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_insertRoom", m_IDParameter, m_DateParameter, s_StartTimeParameter, s_EndTimeParameter, s_TitleParameter, s_U_IDParameter);
        }
    
        public virtual int proc_IsPassReimburse(string r_ID, string isAdmission)
        {
            var r_IDParameter = r_ID != null ?
                new ObjectParameter("R_ID", r_ID) :
                new ObjectParameter("R_ID", typeof(string));
    
            var isAdmissionParameter = isAdmission != null ?
                new ObjectParameter("IsAdmission", isAdmission) :
                new ObjectParameter("IsAdmission", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_IsPassReimburse", r_IDParameter, isAdmissionParameter);
        }
    
        public virtual int proc_IsPassTravel(string t_ID, string isAdmission)
        {
            var t_IDParameter = t_ID != null ?
                new ObjectParameter("T_ID", t_ID) :
                new ObjectParameter("T_ID", typeof(string));
    
            var isAdmissionParameter = isAdmission != null ?
                new ObjectParameter("IsAdmission", isAdmission) :
                new ObjectParameter("IsAdmission", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_IsPassTravel", t_IDParameter, isAdmissionParameter);
        }
    
        public virtual int proc_IsPassVacate(Nullable<int> v_ID, string isAdmission)
        {
            var v_IDParameter = v_ID.HasValue ?
                new ObjectParameter("V_ID", v_ID) :
                new ObjectParameter("V_ID", typeof(int));
    
            var isAdmissionParameter = isAdmission != null ?
                new ObjectParameter("IsAdmission", isAdmission) :
                new ObjectParameter("IsAdmission", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_IsPassVacate", v_IDParameter, isAdmissionParameter);
        }
    
        public virtual ObjectResult<proc_IsReimburse_Result> proc_IsReimburse(string u_ID, Nullable<bool> isApprove)
        {
            var u_IDParameter = u_ID != null ?
                new ObjectParameter("U_ID", u_ID) :
                new ObjectParameter("U_ID", typeof(string));
    
            var isApproveParameter = isApprove.HasValue ?
                new ObjectParameter("IsApprove", isApprove) :
                new ObjectParameter("IsApprove", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_IsReimburse_Result>("proc_IsReimburse", u_IDParameter, isApproveParameter);
        }
    
        public virtual ObjectResult<proc_IsTravel_Result> proc_IsTravel(string u_ID, Nullable<bool> isApprove)
        {
            var u_IDParameter = u_ID != null ?
                new ObjectParameter("U_ID", u_ID) :
                new ObjectParameter("U_ID", typeof(string));
    
            var isApproveParameter = isApprove.HasValue ?
                new ObjectParameter("IsApprove", isApprove) :
                new ObjectParameter("IsApprove", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_IsTravel_Result>("proc_IsTravel", u_IDParameter, isApproveParameter);
        }
    
        public virtual ObjectResult<proc_IsVacate_Result> proc_IsVacate(string u_ID, Nullable<bool> isApprove)
        {
            var u_IDParameter = u_ID != null ?
                new ObjectParameter("U_ID", u_ID) :
                new ObjectParameter("U_ID", typeof(string));
    
            var isApproveParameter = isApprove.HasValue ?
                new ObjectParameter("IsApprove", isApprove) :
                new ObjectParameter("IsApprove", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_IsVacate_Result>("proc_IsVacate", u_IDParameter, isApproveParameter);
        }
    
        public virtual ObjectResult<proc_MyReimburse_Result> proc_MyReimburse(string u_ID)
        {
            var u_IDParameter = u_ID != null ?
                new ObjectParameter("U_ID", u_ID) :
                new ObjectParameter("U_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_MyReimburse_Result>("proc_MyReimburse", u_IDParameter);
        }
    
        public virtual ObjectResult<proc_MyTravel_Result> proc_MyTravel(string u_ID)
        {
            var u_IDParameter = u_ID != null ?
                new ObjectParameter("U_ID", u_ID) :
                new ObjectParameter("U_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_MyTravel_Result>("proc_MyTravel", u_IDParameter);
        }
    
        public virtual ObjectResult<proc_MyVacate_Result> proc_MyVacate(string u_ID)
        {
            var u_IDParameter = u_ID != null ?
                new ObjectParameter("U_ID", u_ID) :
                new ObjectParameter("U_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_MyVacate_Result>("proc_MyVacate", u_IDParameter);
        }
    
        public virtual ObjectResult<proc_Sel_Result> proc_Sel(Nullable<bool> iswifi, Nullable<bool> m_Projection)
        {
            var iswifiParameter = iswifi.HasValue ?
                new ObjectParameter("Iswifi", iswifi) :
                new ObjectParameter("Iswifi", typeof(bool));
    
            var m_ProjectionParameter = m_Projection.HasValue ?
                new ObjectParameter("M_Projection", m_Projection) :
                new ObjectParameter("M_Projection", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_Sel_Result>("proc_Sel", iswifiParameter, m_ProjectionParameter);
        }
    
        public virtual ObjectResult<proc_SelNoread_Result> proc_SelNoread(string id)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_SelNoread_Result>("proc_SelNoread", idParameter);
        }
    
        public virtual ObjectResult<proc_Selread_Result> proc_Selread(string id)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_Selread_Result>("proc_Selread", idParameter);
        }
    }
}
